# Import Pandas file

In [1]:
import pandas as pd

In [2]:
# Explicitly set the first column (index 0) or 'popularity' to string/object
df = pd.read_csv("movies_metadata.csv", dtype={'popularity': str})
print(df)

       adult                              belongs_to_collection    budget  \
0      False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1      False                                                NaN  65000000
2      False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3      False                                                NaN  16000000
4      False  {'id': 96871, 'name': 'Father of the Bride Col...         0
...      ...                                                ...       ...
45461  False                                                NaN         0
45462  False                                                NaN         0
45463  False                                                NaN         0
45464  False                                                NaN         0
45465  False                                                NaN         0

                                                  genres  \
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                         [{'id': 35, 'name': 'Comedy'}]
...                                                  ...
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462                      [{'id': 18, 'name': 'Drama'}]
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464                                                 []
45465                                                 []

                                   homepage      id    imdb_id  \
0      http://toystory.disney.com/toy-story     862  tt0114709
1                                       NaN    8844  tt0113497
2                                       NaN   15602  tt0113228
3                                       NaN   31357  tt0114885
4                                       NaN   11862  tt0113041
...                                     ...     ...        ...
45461  http://www.imdb.com/title/tt6209470/  439050  tt6209470
45462                                   NaN  111109  tt2028550
45463                                   NaN   67758  tt0303758
45464                                   NaN  227506  tt0008536
45465                                   NaN  461257  tt6980792

      original_language               original_title  \
0                    en                    Toy Story
1                    en                      Jumanji
2                    en             Grumpier Old Men
3                    en            Waiting to Exhale
4                    en  Father of the Bride Part II
...                 ...                          ...
45461                fa                      رگ خواب
45462                tl          Siglo ng Pagluluwal
45463                en                     Betrayal
45464                en          Satana likuyushchiy
45465                en                     Queerama

                                                overview  ... release_date  \
0      Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
1      When siblings Judy and Peter discover an encha...  ...   1995-12-15
2      A family wedding reignites the ancient feud be...  ...   1995-12-22
3      Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
4      Just when George Banks has recovered from his ...  ...   1995-02-10
...                                                  ...  ...          ...
45461        Rising and falling between a man and woman.  ...          NaN
45462  An artist struggles to finish his work while a...  ...   2011-11-17
45463  When one of her hits goes wrong, a professiona...  ...   2003-08-01
45464  In a small town live two brothers, one a minis...  ...   1917-10-21
45465  50 years after decriminalisation of homosexual...  ...   2017-06-09

           revenue runtime                                   spoken_languages  \
0      373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1      262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2              0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3       81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4       76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]
...            ...     ...                                                ...
45461          0.0    90.0             [{'iso_639_1': 'fa', 'name': 'فارسی'}]
45462          0.0   360.0                  [{'iso_639_1': 'tl', 'name': ''}]
45463          0.0    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
45464          0.0    87.0                                                 []
45465          0.0    75.0           [{'iso_639_1': 'en', 'name': 'English'}]

         status                                            tagline  \
0      Released                                                NaN
1      Released          Roll the dice and unleash the excitement!
2      Released  Still Yelling. Still Fighting. Still Ready for...
3      Released  Friends are the people who let you be yourself...
4      Released  Just When His World Is Back To Normal... He's ...
...         ...                                                ...
45461  Released         Rising and falling between a man and woman
45462  Released                                                NaN
45463  Released                             A deadly game of wits.
45464  Released                                                NaN
45465  Released                                                NaN

                             title  video vote_average vote_count
0                        Toy Story  False          7.7     5415.0
1                          Jumanji  False          6.9     2413.0
2                 Grumpier Old Men  False          6.5       92.0
3                Waiting to Exhale  False          6.1       34.0
4      Father of the Bride Part II  False          5.7      173.0
...                            ...    ...          ...        ...
45461                       Subdue  False          4.0        1.0
45462          Century of Birthing  False          9.0        3.0
45463                     Betrayal  False          3.8        6.0
45464             Satan Triumphant  False          0.0        0.0
45465                     Queerama  False          0.0        0.0

[45466 rows x 24 columns]

In [4]:
df.info

<bound method DataFrame.info of        adult                              belongs_to_collection    budget  \
0      False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1      False                                                NaN  65000000
2      False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3      False                                                NaN  16000000
4      False  {'id': 96871, 'name': 'Father of the Bride Col...         0
...      ...                                                ...       ...
45461  False                                                NaN         0
45462  False                                                NaN         0
45463  False                                                NaN         0
45464  False                                                NaN         0
45465  False                                                NaN         0

                                                  genres  \
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                         [{'id': 35, 'name': 'Comedy'}]
...                                                  ...
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462                      [{'id': 18, 'name': 'Drama'}]
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464                                                 []
45465                                                 []

                                   homepage      id    imdb_id  \
0      http://toystory.disney.com/toy-story     862  tt0114709
1                                       NaN    8844  tt0113497
2                                       NaN   15602  tt0113228
3                                       NaN   31357  tt0114885
4                                       NaN   11862  tt0113041
...                                     ...     ...        ...
45461  http://www.imdb.com/title/tt6209470/  439050  tt6209470
45462                                   NaN  111109  tt2028550
45463                                   NaN   67758  tt0303758
45464                                   NaN  227506  tt0008536
45465                                   NaN  461257  tt6980792

      original_language               original_title  \
0                    en                    Toy Story
1                    en                      Jumanji
2                    en             Grumpier Old Men
3                    en            Waiting to Exhale
4                    en  Father of the Bride Part II
...                 ...                          ...
45461                fa                      رگ خواب
45462                tl          Siglo ng Pagluluwal
45463                en                     Betrayal
45464                en          Satana likuyushchiy
45465                en                     Queerama

                                                overview  ... release_date  \
0      Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
1      When siblings Judy and Peter discover an encha...  ...   1995-12-15
2      A family wedding reignites the ancient feud be...  ...   1995-12-22
3      Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
4      Just when George Banks has recovered from his ...  ...   1995-02-10
...                                                  ...  ...          ...
45461        Rising and falling between a man and woman.  ...          NaN
45462  An artist struggles to finish his work while a...  ...   2011-11-17
45463  When one of her hits goes wrong, a professiona...  ...   2003-08-01
45464  In a small town live two brothers, one a minis...  ...   1917-10-21
45465  50 years after decriminalisation of homosexual...  ...   2017-06-09

           revenue runtime                                   spoken_languages  \
0      373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1      262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2              0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3       81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4       76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]
...            ...     ...                                                ...
45461          0.0    90.0             [{'iso_639_1': 'fa', 'name': 'فارسی'}]
45462          0.0   360.0                  [{'iso_639_1': 'tl', 'name': ''}]
45463          0.0    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
45464          0.0    87.0                                                 []
45465          0.0    75.0           [{'iso_639_1': 'en', 'name': 'English'}]

         status                                            tagline  \
0      Released                                                NaN
1      Released          Roll the dice and unleash the excitement!
2      Released  Still Yelling. Still Fighting. Still Ready for...
3      Released  Friends are the people who let you be yourself...
4      Released  Just When His World Is Back To Normal... He's ...
...         ...                                                ...
45461  Released         Rising and falling between a man and woman
45462  Released                                                NaN
45463  Released                             A deadly game of wits.
45464  Released                                                NaN
45465  Released                                                NaN

                             title  video vote_average vote_count
0                        Toy Story  False          7.7     5415.0
1                          Jumanji  False          6.9     2413.0
2                 Grumpier Old Men  False          6.5       92.0
3                Waiting to Exhale  False          6.1       34.0
4      Father of the Bride Part II  False          5.7      173.0
...                            ...    ...          ...        ...
45461                       Subdue  False          4.0        1.0
45462          Century of Birthing  False          9.0        3.0
45463                     Betrayal  False          3.8        6.0
45464             Satan Triumphant  False          0.0        0.0
45465                     Queerama  False          0.0        0.0

[45466 rows x 24 columns]>

In [5]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [6]:
df["runtime"]

0         81.0
1        104.0
2        101.0
3        127.0
4        106.0
         ...
45461     90.0
45462    360.0
45463     90.0
45464     87.0
45465     75.0
Name: runtime, Length: 45466, dtype: float64

In [7]:
df[["runtime","revenue"]]

       runtime      revenue
0         81.0  373554033.0
1        104.0  262797249.0
2        101.0          0.0
3        127.0   81452156.0
4        106.0   76578911.0
...        ...          ...
45461     90.0          0.0
45462    360.0          0.0
45463     90.0          0.0
45464     87.0          0.0
45465     75.0          0.0

[45466 rows x 2 columns]

In [8]:
# df.iloc[row_start:row_stop, column_start:column_stop, 1:3]
df.iloc[:, 1:3]

                                   belongs_to_collection    budget
0      {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1                                                    NaN  65000000
2      {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3                                                    NaN  16000000
4      {'id': 96871, 'name': 'Father of the Bride Col...         0
...                                                  ...       ...
45461                                                NaN         0
45462                                                NaN         0
45463                                                NaN         0
45464                                                NaN         0
45465                                                NaN         0

[45466 rows x 2 columns]

In [9]:
df.iloc[0]  # first row

adult                                                                False
belongs_to_collection    {'id': 10194, 'name': 'Toy Story Collection', ...
budget                                                            30000000
genres                   [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
homepage                              http://toystory.disney.com/toy-story
id                                                                     862
imdb_id                                                          tt0114709
original_language                                                       en
original_title                                                   Toy Story
overview                 Led by Woody, Andy's toys live happily in his ...
popularity                                                       21.946943
poster_path                               /rhIRbceoE9lR4veEXuwCC2wARtG.jpg
production_companies        [{'name': 'Pixar Animation Studios', 'id': 3}]
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    1995-10-30
revenue                                                        373554033.0
runtime                                                               81.0
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                                                                NaN
title                                                            Toy Story
video                                                                False
vote_average                                                           7.7
vote_count                                                          5415.0
Name: 0, dtype: object

In [10]:
df.iloc[-1] # last row

adult                                                                False
belongs_to_collection                                                  NaN
budget                                                                   0
genres                                                                  []
homepage                                                               NaN
id                                                                  461257
imdb_id                                                          tt6980792
original_language                                                       en
original_title                                                    Queerama
overview                 50 years after decriminalisation of homosexual...
popularity                                                        0.163015
poster_path                               /s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg
production_companies                                                    []
production_countries      [{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]
release_date                                                    2017-06-09
revenue                                                                0.0
runtime                                                               75.0
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                                                                NaN
title                                                             Queerama
video                                                                False
vote_average                                                           0.0
vote_count                                                             0.0
Name: 45465, dtype: object

# 16 09 2026

In [12]:
print(df.columns)

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')

In [13]:
print(df.columns.tolist())

['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count']

In [14]:
print(df.shape)

(45466, 24)

In [15]:
print(df.ndim)

2

In [17]:
print(df.dtypes)

adult                        str
belongs_to_collection        str
budget                       str
genres                       str
homepage                     str
id                           str
imdb_id                      str
original_language            str
original_title               str
overview                     str
popularity                   str
poster_path                  str
production_companies         str
production_countries         str
release_date                 str
revenue                  float64
runtime                  float64
spoken_languages             str
status                       str
tagline                      str
title                        str
video                     object
vote_average             float64
vote_count               float64
dtype: object

In [19]:
print(df.sample())

       adult belongs_to_collection budget                          genres  \
32218  False                   NaN      0  [{'id': 35, 'name': 'Comedy'}]

      homepage     id    imdb_id original_language  \
32218      NaN  27169  tt1554966                en

                                    original_title  \
32218  Gabriel Iglesias: I'm Not Fat... I'm Fluffy

                                                overview  ... release_date  \
32218  Gabriel Iglesias entertains a packed house at ...  ...   2009-11-08

      revenue runtime spoken_languages    status  tagline  \
32218     0.0    60.0               []  Released      NaN

                                             title  video vote_average  \
32218  Gabriel Iglesias: I'm Not Fat... I'm Fluffy  False          6.7

      vote_count
32218       16.0

[1 rows x 24 columns]

In [20]:
df = df.rename(
    columns={
        "genres" : "categories"
    }
)

In [22]:
print(df.dtypes)

adult                        str
belongs_to_collection        str
budget                       str
categories                   str
homepage                     str
id                           str
imdb_id                      str
original_language            str
original_title               str
overview                     str
popularity                   str
poster_path                  str
production_companies         str
production_countries         str
release_date                 str
revenue                  float64
runtime                  float64
spoken_languages             str
status                       str
tagline                      str
title                        str
video                     object
vote_average             float64
vote_count               float64
dtype: object

In [5]:
students = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": [
        "Rahul", "Amit", "Priya", "Neha",
        "Arjun", "Sneha", "Rohan", "Kavya"
    ],
    "Age": [21, 22, 20, 21, 23, 20, 22, 21],
    "Gender": [
        "Male", "Male", "Female", "Female",
        "Male", "Female", "Male", "Female"
    ],
    "City": [
        "Mumbai", "Pune", "Mumbai", "Delhi",
        "Pune", "Mumbai", "Delhi", "Nashik"
    ],
    "Marks": [85, 72, 92, 64, 76, 95, 58, 88],
    "Attendance": [90, 78, 96, 82, 75, 98, 68, 91]
}

df = pd.DataFrame(students)

print(df)

   Student_ID   Name  Age  Gender    City  Marks  Attendance
0         101  Rahul   21    Male  Mumbai     85          90
1         102   Amit   22    Male    Pune     72          78
2         103  Priya   20  Female  Mumbai     92          96
3         104   Neha   21  Female   Delhi     64          82
4         105  Arjun   23    Male    Pune     76          75
5         106  Sneha   20  Female  Mumbai     95          98
6         107  Rohan   22    Male   Delhi     58          68
7         108  Kavya   21  Female  Nashik     88          91

In [36]:
df[["Name"]]
# df["Name"]

    Name
0  Rahul
1   Amit
2  Priya
3   Neha
4  Arjun
5  Sneha
6  Rohan
7  Kavya

In [41]:
df[["Name","Marks","City"]]

    Name  Marks    City
0  Rahul     85  Mumbai
1   Amit     72    Pune
2  Priya     92  Mumbai
3   Neha     64   Delhi
4  Arjun     76    Pune
5  Sneha     95  Mumbai
6  Rohan     58   Delhi
7  Kavya     88  Nashik

In [45]:
df.iloc[:, 1]

0    Rahul
1     Amit
2    Priya
3     Neha
4    Arjun
5    Sneha
6    Rohan
7    Kavya
Name: Name, dtype: str

In [46]:
df.iloc[:, 1:4]

    Name  Age  Gender
0  Rahul   21    Male
1   Amit   22    Male
2  Priya   20  Female
3   Neha   21  Female
4  Arjun   23    Male
5  Sneha   20  Female
6  Rohan   22    Male
7  Kavya   21  Female

In [49]:
df.iloc[0]
#OR
df.iloc[:1]

   Student_ID   Name  Age Gender    City  Marks  Attendance
0         101  Rahul   21   Male  Mumbai     85          90

In [50]:
#index 0 3 5
df.iloc[[0,3,5]]

   Student_ID   Name  Age  Gender    City  Marks  Attendance
0         101  Rahul   21    Male  Mumbai     85          90
3         104   Neha   21  Female   Delhi     64          82
5         106  Sneha   20  Female  Mumbai     95          98

In [61]:
print(df.iloc[2].Name)

#OR
print(df.iloc[2,1:2])

Priya
Name    Priya
Name: 2, dtype: object

In [ ]:
# from 0 to 3 name age marks
df.iloc[0:4, [1, 2, 5]]

#OR

df.loc[:4,["Name","Age","Marks"]]

    Name  Age  Marks
0  Rahul   21     85
1   Amit   22     72
2  Priya   20     92
3   Neha   21     64
4  Arjun   23     76

In [ ]:
# print data with marks more than 80
df[df["Marks"] > 80] # same will be aplied for other conditions

   Student_ID   Name  Age  Gender    City  Marks  Attendance
0         101  Rahul   21    Male  Mumbai     85          90
2         103  Priya   20  Female  Mumbai     92          96
5         106  Sneha   20  Female  Mumbai     95          98
7         108  Kavya   21  Female  Nashik     88          91

In [ ]:
# marks are greater than 80 and attendance is greater than 95 
df[(df["Marks"] > 80) & (df["Attendance"] > 95)]

   Student_ID   Name  Age  Gender    City  Marks  Attendance
2         103  Priya   20  Female  Mumbai     92          96
5         106  Sneha   20  Female  Mumbai     95          98

In [ ]:
# city is mumbai and pune
print(df[(df["City"] == "Mumbai") | (df["City"] == "Pune")])

   Student_ID   Name  Age  Gender    City  Marks  Attendance
0         101  Rahul   21    Male  Mumbai     85          90
1         102   Amit   22    Male    Pune     72          78
2         103  Priya   20  Female  Mumbai     92          96
4         105  Arjun   23    Male    Pune     76          75
5         106  Sneha   20  Female  Mumbai     95          98

In [ ]:
# city is not mumbai
print(df[~(df["City"] == "Mumbai")])

   Student_ID   Name  Age  Gender    City  Marks  Attendance
1         102   Amit   22    Male    Pune     72          78
3         104   Neha   21  Female   Delhi     64          82
4         105  Arjun   23    Male    Pune     76          75
6         107  Rohan   22    Male   Delhi     58          68
7         108  Kavya   21  Female  Nashik     88          91

In [77]:
# names where marks are above 80
df[df["Marks"] > 80]["Name"]

#OR 

print(df.loc[df["Marks"] > 80, "Name"])

0    Rahul
2    Priya
5    Sneha
7    Kavya
Name: Name, dtype: str

In [ ]:
# OR(|) using isin
print(df[df["City"].isin(["Mumbai","Pune"])])

   Student_ID   Name  Age  Gender    City  Marks  Attendance
0         101  Rahul   21    Male  Mumbai     85          90
1         102   Amit   22    Male    Pune     72          78
2         103  Priya   20  Female  Mumbai     92          96
4         105  Arjun   23    Male    Pune     76          75
5         106  Sneha   20  Female  Mumbai     95          98

# 17 09 2026

In [1]:
import pandas as pd

In [6]:
print(df[df["Marks"].between(70,90)])

   Student_ID   Name  Age  Gender    City  Marks  Attendance
0         101  Rahul   21    Male  Mumbai     85          90
1         102   Amit   22    Male    Pune     72          78
4         105  Arjun   23    Male    Pune     76          75
7         108  Kavya   21  Female  Nashik     88          91

In [9]:
print(df[df["Name"].str.startswith("R")])

   Student_ID   Name  Age Gender    City  Marks  Attendance
0         101  Rahul   21   Male  Mumbai     85          90
6         107  Rohan   22   Male   Delhi     58          68

In [10]:
print(df[df["Name"].str.contains("a")])

   Student_ID   Name  Age  Gender    City  Marks  Attendance
0         101  Rahul   21    Male  Mumbai     85          90
2         103  Priya   20  Female  Mumbai     92          96
3         104   Neha   21  Female   Delhi     64          82
5         106  Sneha   20  Female  Mumbai     95          98
6         107  Rohan   22    Male   Delhi     58          68
7         108  Kavya   21  Female  Nashik     88          91

In [12]:
print(df.query("Marks > 80"))

   Student_ID   Name  Age  Gender    City  Marks  Attendance
0         101  Rahul   21    Male  Mumbai     85          90
2         103  Priya   20  Female  Mumbai     92          96
5         106  Sneha   20  Female  Mumbai     95          98
7         108  Kavya   21  Female  Nashik     88          91

In [14]:
print(df.query("Marks > 80 and Attendance > 90"))

   Student_ID   Name  Age  Gender    City  Marks  Attendance
2         103  Priya   20  Female  Mumbai     92          96
5         106  Sneha   20  Female  Mumbai     95          98
7         108  Kavya   21  Female  Nashik     88          91

In [15]:
print(df.at[2,"Name"])  # works like loc , at takes index name(label)

Priya

In [16]:
print(df.iat[2,1])  # works like iloc , iat takes index number #position

Priya

In [17]:
# change marks of rahul to 89
df.loc[df["Name"] == "Rahul","Marks"] = 89
print(df)

   Student_ID   Name  Age  Gender    City  Marks  Attendance
0         101  Rahul   21    Male  Mumbai     89          90
1         102   Amit   22    Male    Pune     72          78
2         103  Priya   20  Female  Mumbai     92          96
3         104   Neha   21  Female   Delhi     64          82
4         105  Arjun   23    Male    Pune     76          75
5         106  Sneha   20  Female  Mumbai     95          98
6         107  Rohan   22    Male   Delhi     58          68
7         108  Kavya   21  Female  Nashik     88          91

In [22]:
df["Result"] = "Pass"

In [23]:
df.loc[df["Marks"] < 60,"Result"] = "Fail"
print(df)

   Student_ID   Name  Age  Gender    City  Marks  Attendance Result
0         101  Rahul   21    Male  Mumbai     89          90   Pass
1         102   Amit   22    Male    Pune     72          78   Pass
2         103  Priya   20  Female  Mumbai     92          96   Pass
3         104   Neha   21  Female   Delhi     64          82   Pass
4         105  Arjun   23    Male    Pune     76          75   Pass
5         106  Sneha   20  Female  Mumbai     95          98   Pass
6         107  Rohan   22    Male   Delhi     58          68   Fail
7         108  Kavya   21  Female  Nashik     88          91   Pass

In [24]:
students = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Rahul", "Amit", "Priya", "Neha", "Arjun"],
    "Marks": [85, 72, 92, 64, 38],
    "Attendance": [90, 78, 96, 82, 65]
}

df = pd.DataFrame(students)

print(df)

   Student_ID   Name  Marks  Attendance
0         101  Rahul     85          90
1         102   Amit     72          78
2         103  Priya     92          96
3         104   Neha     64          82
4         105  Arjun     38          65

In [25]:
# 1 student above 80
print(df[df["Marks"] > 80].iloc[0:1])

   Student_ID   Name  Marks  Attendance
0         101  Rahul     85          90

In [26]:
# 2 show student with poor attendace with less than 75 %  
print(df[df["Attendance"] < 75])

   Student_ID   Name  Marks  Attendance
4         105  Arjun     38          65

In [34]:
# 3 student who scored above 80 and attendance below 90
print(df[(df["Marks"] > 80) & (df["Attendance"] < 90)])   # put <= 90

Empty DataFrame
Columns: [Student_ID, Name, Marks, Attendance]
Index: []